### ISSUE TITLE
Please bring this project back to life.

### ISSUE THREAD

**Issue by thibaultmol** [softace/kdirstat#1]
As a 'switching to linux from Windows' user, I want to be able to use the original Kdirstat instead of Windirstat.

Can someone please bring this project back to life?

**Comment by jarl-dk** [comment]
Hi @thibaultmol . I appreciate your interest...

I am not the original author of KDirStat. I discovered some time ago that DirStat was no longer actively maintained. I would love to see this application live up again. I am a proficient C++/Qt developer. So as a starting point I did a import to github. But I have never had the time to get it up and running with that latest libraries... Basically I am also looking for people who would like to participate in getting KDirStat  up and running again.

**Comment by shundhammer** [comment]
Use the newer, better, shinier QDirStat:

https://github.com/shundhammer/qdirstat

**Comment by jarl-dk** [comment]
@shundhammer : Fantastic. Welcome back to the newer, better, shinier QDirStat.
@shundhammer: Thanks a lot for taking the project back to life again.

**Comment by jarl-dk** [comment]
I have updated the project description and added a README.md file to redirect people to the newer project.

**Comment by shundhammer** [comment]
@jarl-dk : Just rebase from kdirstat master; I updated the README.md there as well.
